name: drush-toolbox
permalink: /releases/:title.html
baseurl: /drush-toolbox
project:
  title: Drush Developers' Toolbox
  short_name: drush-toolbox
  project_status: 1
  link: http://github.com/zroger/drush-toolbox
  type: Modules
  user: zroger